### ISSUE TITLE
Named Routing

### ISSUE THREAD

**Issue by RitwikSingh28** [hackslash-nitp/cura#52]
We have to improve routing in our application by using namedRoutes, as this will allow our app to have a cleaner, modular and maintainable design. 

For interested persons:
**Documentation** - 
https://docs.flutter.dev/cookbook/navigation/named-routes   
https://medium.flutterdevs.com/navigate-with-named-routes-in-flutter-5de44922789e

Deadline to complete the task - **2** days after having been assigned

@rani620 @SUSAJJIT @KarnikaKhandelwal @kmansimtg @Shazeb-Khan 
If any of you are interested in solving this issue, kindly mention here in the comments, so that I may assign it to you.

Please reply before 27 October if you are interested.

**Comment by Devank-Sachdeva** [comment]
Can u please assign this to me. I want to work on this issue

**Comment by RitwikSingh28** [comment]
@Devank-Sachdeva
Thanks for your interest in this :smile: Before I assign it to you, there are some things that I would like you to keep in mind while working on this issue
- Add routes in the main.dart file, and the names of these routes should be self-describing
- Replace with named routes everywhere 
- And make sure that the entire app has only a single MaterialApp.

Deadline to complete - **27 October 11:59 A.M.**
If you agree to these conditions, or have any suggestions, please let us know

**Comment by Devank-Sachdeva** [comment]
I agree to these conditions and will start working right away.

**Comment by Devank-Sachdeva** [comment]
I would suggest you to make all the route related work in a separate file because we have to use onGenerateRoute instead of normal route map as route map cannot pass the dynamic data across pages as i am seeing in your Login page and chat screen you need to pass the dynamic user data across pages.
This is just to avoid mess in main.dart although it can be done in main.dart if u say so.

Attaching a [guide](https://resocoder.com/2019/04/27/flutter-routes-navigation-parameters-named-routes-ongenerateroute/) if you want to have a look on onGenerateRoutes.

**Comment by Devank-Sachdeva** [comment]
@RitwikSingh28 can u review it and tell me if any change is required.

**Comment by RitwikSingh28** [comment]
@Devank-Sachdeva I have reviewed your changes, and I have provided the appropriate feedback as well. Please do look through it once.
